### ISSUE TITLE
The game just crashes after i join a game

### ISSUE THREAD

**Issue by ZLOKY** [M-FeD/Fedoraware#14] opened 2021-09-08 10:33 UTC
For me when i join a server/casual after 15 seconds my game just crashes pls help what do i do

**Comment by ZLOKY** [comment] 2021-09-08 10:35
HELP NOW I WANA TRY THE CHEAT

**Comment by JAGNEmk** [comment] 2021-09-08 10:58
There are multiple issues, closing this, please go to the other thread.

**Comment by M-FeD** [comment] 2021-09-09 13:48
This can be caused by many things, but attempting to load a custom skybox if sv_pure bypass is disabled will crash you.

**Closed by M-FeD** 2021-09-09 13:48 UTC
Labels: bug, duplicate
