### ISSUE TITLE
For me when i join a server/casual after 15 seconds my game just crashes pls help what do i do

### ISSUE THREAD

**Issue by ZLOKY** [M-FeD/Fedoraware#13] opened 2021-09-08 10:32 UTC

**Comment by JAGNEmk** [comment] 2021-09-08 10:57
Well this is quite strange! What Windows version are you on? (i.e. Windows 10 x64 bit) Also what Visual Studio C++ Redistributables do you have installed? (i.e. Visual Studio C++ Redist. 2015 x64, 2019 x86, etc)
And what .NET framework version do you have installed? (i.e. version 4.7)

Ever since the imgui menu update users have been reporting issues, even my build is broken (doesn't inject), we're working on providing support and fixing issues!

**Comment by M-FeD** [comment] 2021-09-08 12:36
Are you building in debug? That crashes a lot more for me than release

**Comment by ZLOKY** [comment] 2021-09-08 12:46
Yes i am building it in debug.  and btw "JAGNEmk" are u the one that makes the dev texture if u are plz add me agen on steam cuz u just removed me on steam srry bad english. hers my steam if u are the persion that made the dev texture https://steamcommunity.com/profiles/76561199109207528/  if u ware the persion and if u dont remeber who i am i am the youtuber that makes tf2 cheating videos and my name on youtube is also ZLOKY. :3

**Comment by M-FeD** [comment] 2021-09-08 12:54
> Yes i am building it in debug. 

Strongly suggest you switch to release, should make a lot of crashes not happen although if you can find out where the crashes are coming from in debug that would be nice too

**Comment by JAGNEmk** [comment] 2021-09-08 14:22
Solution is to build in release x86 always, closing this and adding to the readme

**Comment by M-FeD** [comment] 2021-09-09 13:45
This is caused by the cathook identify function. 
![image](https://user-images.githubusercontent.com/31779182/132697417-374a4fd6-8943-4940-a2b5-a2fed6bf3b0d.png)
If you know how to fix this, please inform me

**Comment by M-FeD** [comment] 2021-09-09 22:56
I commented it out for now, lmk if you still get crashes in a similar way

**Closed by M-FeD** 2021-09-09 22:56 UTC
Labels: bug
